apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwMi5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYXpoemRYTmxjanBCWkcxcGJrQXhNak09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: "2023-02-21T05:13:53Z"
  name: jfrogcred
  namespace: valaxy
  resourceVersion: "5604"
  uid: 1dd1b4c0-5005-40d4-b062-ce4f2df3091b
type: kubernetes.io/dockerconfigjson
